-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table status
create table status (
    id_status integer generated by default as identity,
    description varchar(255),
    name varchar(255),
    primary key (id_status)
 );

 -- changeset script:2
 -- comment: Creation table priority
create table priority (
    id_priority integer generated by default as identity,
    description varchar(255),
    name varchar(255),
    primary key (id_priority)
);

-- changeset script:3
-- comment: Creation table task
create table task (
    id_task integer generated by default as identity,
    begin_date timestamp(6),
    description varchar(255),
    end_date timestamp(6),
    name varchar(255),
    id_priority_fk integer,
    id_status_fk integer,
    primary key (id_task)
);

---- changeset script:4
---- comment: Creation table role
--create table role (
--    id integer generated by default as identity,
--    name varchar(255),
--    primary key (id)
--);
--
---- changeset script:5
---- comment: Creation table usuario_rol
--create table usuario_rol (
--    id_usuario integer not null,
--    id_rol integer not null
--);
--
-- changeset script:11
-- comment: Creation status
INSERT INTO status(name, description) VALUES
    ( 'Iniciada', 'Tarea iniciada' ),
    ( 'En proceso', 'Tarea en proceso' ),
	( 'Terminada', 'Tarea terminada' );
--
-- changeset script:12
-- comment: Creation products
INSERT INTO priority(name, description) VALUES
    ( 'Bajo', 'Prioridad Baja' ),
    ( 'Normal', 'Prioridad Normal' ),
    ( 'Urgente', 'Prioridad Urgente' );

-- changeset script:13
-- comment: Creation task
INSERT INTO task(name, description, begin_date, end_date, id_priority_fk, id_status_fk) VALUES
	( 'Desayuno', 'Hacer Desayuno', '2020-06-14 00:00:00', '2020-06-14 00:00:00', 1, 1 ),
	( 'Almuerzo', 'Hacer Almuerzo', '2020-06-14 00:00:00', '2020-06-14 00:00:00', 1, 1 ),
	( 'Cena', 'Hacer Cena', '2020-06-14 00:00:00', '2020-06-14 00:00:00', 1, 1 );

---- changeset script:14
---- comment: Creation Roles
--INSERT INTO role(name) VALUES
--	( 'ADMIN'),
--	( 'CUSTOMER');
--
---- changeset script:15
---- comment: assign roles
--INSERT INTO usuario_rol(id_usuario, id_rol) VALUES
--	( 1, 1),
--	( 1, 2),
--	( 2, 2);

